// GET LATEST STOCKS
export const GET_LATEST_PRICE_REQUEST = "GET_LATEST_PRICE_REQUEST";
export const GET_LATEST_PRICE_SUCCESS = "GET_LATEST_PRICE_SUCCESS";
export const GET_LATEST_PRICE_FAILED = "GET_LATEST_PRICE_FAILED";

export const CLEAR_ALL = "CLEAR_ALL";
