// GET COMPANY INFO
export const GET_COMPANY_INFO_REQUEST = "GET_COMPANY_INFO_REQUEST";
export const GET_COMPANY_INFO_SUCCESS = "GET_COMPANY_INFO_SUCCESS";
export const GET_COMPANY_INFO_FAILED = "GET_COMPANY_INFO_FAILED";
